name = "dating-app-frontend"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

main = ".open-next/worker.js"

# 环境变量配置
[env.production]
vars = { API_BASE_URL = "https://dating-app-backend.your-subdomain.workers.dev" }

[env.preview]
vars = { API_BASE_URL = "https://dating-app-backend-preview.your-subdomain.workers.dev" }
